#!/usr/bin/env python3
# Command line for script 
"""
:param str input_csv_file: Path to input file

:param str output_csv_file: Path to output file
"""
import argparse
from pipeline.steps.tokenize_text import tokenize_text

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Command for script tokenize_text')
    parser.add_argument('--input-csv-file', type=str, 
            required=True, help="Path to input file")
    parser.add_argument('--output-csv-file', type=str, 
            required=True, help="Path to output file")
    args = parser.parse_args()

    tokenize_text(args.input_csv_file, args.output_csv_file)
